# tomcat
server:
  port: 8097
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    # 最大线程数
    max-threads: 1000
    max-http-header-size: 8096
    # 设置tomcat的basedir
    basedir: ${user.home}/tomcat/tmp
    # 最大连接数
    max-connections: 2000
# spring
spring:
  application:
    name: shianxian-zipkin

management:
  metrics:
    web:
      server:
        auto-time-requests: false

# eureka
eurekaServer:
  host: 10.18.9.51
  user: admin
  password: 123456
  # eureka端口1
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaServer.user}:${eurekaServer.password}@${eurekaServer.host}:${eurekaServer.port}/eureka
  instance:
    prefer-ip-address: true # 以IP地址注册到服务中心，相互注册使用IP地址
    instance-id: ${spring.application.name}:${server.port}


# 日志
logging:
  level:
    root: INFO
  config: classpath:log/logback-spring-test.xml